ThemeOverlayApplier: Catch a potential NPE.
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.om.OverlayIdentifier android.content.om.FabricatedOverlay.getIdentifier()' on a null object reference

AICP: Switch to a simple null check

Signed-off-by: spezi77 <spezi7713@gmx.net>
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
Change-Id: I0145b5c1e3cdfece2024fe234c382b559014b4f8