Revert "BiometricScheduler: Cancel operation if not idle"
This reverts commit 3c19cd21995fdb799787ab1e059bba9f21ebf1b9.

Reason:

frameworks/base/services/..../biometrics/sensors/BiometricScheduler.java:261:
  error: cannot find symbol
            cancelInternal(mCurrentOperation);
            ^
  symbol:   method cancelInternal(BiometricSchedulerOperation)
  location: class BiometricScheduler
1 error

Change-Id: I59c8f90abb651baabcc43dbc7faf18eb97c1c54c