[SQUASH] gmscompat: switch to external GmsCompat app
 * merge recent merges from https://github.com/ProtonAOSP/android_frameworks_base/commits/sc-v2
 * commit history: https://github.com/semdoc/frameworks_base/commits/s12.1-gmscompat

1. gmscompat: hide privileged FontManager service

commit 9b660d35de8481f05139e160e4fd5c6e5be6986c
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Mon Mar 7 16:22:16 2022 +0200

2. gmscompat: fix location service regression

commit 72fe580db20f4d294571983e2cd3ae254640f6b7
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Sun Mar 6 22:38:07 2022 +0200

3. gmscompat: document PhenotypeFlag provider workaround

commit d41a4f61321e02538deafd6056e6e6af03855bae
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Sun Mar 6 22:30:38 2022 +0200

4. gmscompat: improve userId-related shims

    Current approach is fragile: GMS always obtains UserHandle of the primary ("Owner") user and
    tries to use it, which is a privileged operation if GMS is installed in the non-primary user profile.
    It's worked around by unconditionally replacing UserHandle with the current one in all methods that
    GMS calls, which will break each time new GMS version makes use of a new UserHandle-accepting method.

    With the new approach, GMS gets access only to the current UserHandle which is made
    to look like a UserHandle of the primary user.

commit fe026941a61ffa2f17fa461796f03c616566cf57
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Wed Feb 2 15:47:53 2022 +0200

5. gmscompat: use correct "isApplicationUid" check

commit 4f391a039fabf82f1b71ce97c97005c4885d8bb8
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Tue Feb 1 17:48:42 2022 +0200

6. gmscompat: defer isGmsApp() check

commit 586d4a19c3ad04f305c17a3c90b6b66fc956e326
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Wed Feb 2 12:18:25 2022 +0200

7. gmscompat: account removal workaround

commit b8d52052729f06e25ff3a5315813bebcc4e77163
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Sat Feb 5 11:49:40 2022 +0200

8. gmscompat: mark public ModuleLoadState fields final

commit 18be294e5cce2cfbbef95a2c09cdf7b8282dc797
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Sat Mar 5 19:20:08 2022 +0200

9. gmscompat: optimize file path check

    getAbsolutePath() performs needless checks

commit 239b9a27ef47e6798c1a82bcd2cf182d2a6a8ec8
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Sat Mar 5 19:18:02 2022 +0200


10. make DownloadManager.query() a no-op when INTERNET permission is revoked

commit 9601d11f3467465dc1d118be4e71f6e95a2236b2
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Sat Feb 5 11:08:55 2022 +0200

11. gmscompat: fix TOCTOU race

commit 5b04a3680d19d9be256fb6bb016a9567ae20e109
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Sat Mar 5 19:12:51 2022 +0200

12. gmscompat: simplify AppIntegrityManager shim

commit 45ed6e24bd5e5378c339e247b287283eeabef077
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Sat Mar 5 19:01:32 2022 +0200

13. gmscompat: Improve GMS package info exception handling

commit 2b981f453fe0f9f6db0040736ff1aedb630375f5
Author: Danny Lin <danny@kdrag0n.dev>
Date:   Sat Feb 19 23:56:40 2022 -0800

14. gmscompat: Minor code style fixes

commit f1c34ff7db4b5e59eb8404714e917f54a4747c07
Author: Danny Lin <danny@kdrag0n.dev>
Date:   Thu Feb 17 21:59:01 2022 -0800

15. gmscompat: hide UWB system feature

commit 1fc1df17448c062aaca5d505abeb0affe121eabc
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Thu Feb 17 22:20:38 2022 +0200

16. gmscompat: compatibility with updated Dynamite module loading sequence

    There's now additional File.lastModified() checks that happen outside
    the main module loading sequence.

commit 0195d605adc4feb4ab876859cdfad351e3052ff2
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Tue Feb 15 19:27:06 2022 +0200

17. gmscompat: enable on-demand Dynamite modules

commit 44c98f47e04a6310bec5c8fd84a3d894c3af027e
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Tue Feb 15 18:57:25 2022 +0200

18. grant Location permission to GmsCompatApp by default

commit 6b670379f350a073017f1f0f669e9b85b361be5b
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Sun Feb 13 18:20:25 2022 +0200

19. gmscompat: perform binder redirection check in IGmsCallbacks interface

commit b68a262a210ce8bdaf1e604d6ab1ad196fd8118e
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Wed Feb 9 15:30:10 2022 +0200

20. gmscompat: add BinderRedirector

commit 7508863e00ecb7b4e57d70823a3eb0747c1fa0fa
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Wed Feb 9 15:25:29 2022 +0200

21. gmscompat: add HybridBinder

commit b5c7c125d01e497950b0226ec1e83c18b2f7d9a0
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Wed Feb 9 15:06:30 2022 +0200

22. gmscompat: simplify initialization

commit dfbe213e84cb4716e11e35955d4dbe429891b4f6
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Mon Jan 31 19:55:48 2022 +0200

23. don't auto-grant special runtime permissions after update

commit abc150f3d3890b3f471fdb5133f5c98a34885805
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Mon Jan 10 13:33:38 2022 +0200

24. gmscompat: make connection to GmsCompatApp unbreakable

commit 4878bd7f354a68fa11ba20d1c89f1c5d210933a4
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Mon Jan 24 18:54:25 2022 +0200

25. gmscompat: don't make all services foreground

    Instead, rely on an external foreground app to bind to GMS, which
    allows GMS to start regular services.

commit 8e4a3d4404f394a4bf5de980a123fcdab9e11206
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Fri Jan 21 21:44:14 2022 +0200

26. gmscompat: improve location services compatibility

commit 348d3430e7323427509be8d07c005be5c62315bd
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Fri Jan 21 21:40:07 2022 +0200

27. make DownloadManager.enqueue() a no-op when INTERNET permission is revoked

commit 409141b1ecfaecbf8faa24f3ac06a4330a7372f4
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Mon Jan 10 15:50:33 2022 +0200

28. Revert "gmscompat: set foregroundServiceType of location services"

    This reverts commit 8ec949adf42a16360f23e2986c05316dbf99bf16.

commit 89d4a433e25e56024e686ddbaad8ef734b009f96
Author: Daniel Micay <danielmicay@gmail.com>
Date:   Sat Jan 29 01:23:35 2022 -0500

29. gmscompat: don't stub out PackageManager.getSharedLibraries()

    Play Store uses list of shared libraries to filter out apps with missing dependencies.

commit f48659ac520732a3457a3651c7675491014d347c
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Thu Jan 13 21:38:26 2022 +0200

30. gmscompat: enable Play {Asset, Feature} Delivery

    Play Store uses a similar getRunningAppProcesses()-based "is client foreground"
    check as Play Services does, so enable the same workaround for it as well.

commit 9cac2d51d40c547b69c0b08078bad7607954c3b1
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Wed Jan 12 21:52:27 2022 +0200

31. gmscompat: improve account sign-in UI

    GMS tries to access BackupService after sign-in, but doesn't have the permission
    to do so. This manifests itself in the UI as a never-ending spinner.

commit e093598b151b7fee46bf36de62acd9cebf9b144c
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Mon Jan 10 10:05:02 2022 +0200

32. gmscompat: add recently bound pids to getRunningAppProcesses() result

    Play Games Services relies on ActivityManager.getRunningAppProcesses()
    to figure out whether its client is running.
    Unprivileged apps see only their own processes.

commit c634d4c57ea84df7b2d377f5793951ce89d4ddef
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Tue Dec 14 17:33:44 2021 +0200

33. Allow PackageInstaller UI to become hidden if it starts another activity

    In some cases, most commonly when the caller doesn't yet have the
    REQUEST_INSTALL_PACKAGES permission, PackageInstaller UI gets paused as
    it calls startActivity() as part of the confirmation process.
    Previous change failed to take this into account, which caused callers to
    receive the "confirmation declined" result immediately.

commit 09845379035b57f7ab2f29e0033fd45bfc50b9c7
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Thu Jan 6 17:29:47 2022 +0200

34. gmscompat: set foregroundServiceType of location services

    Without it, location access gets throttled after a few minutes.

commit b3798f13e69f223dd07988ac447e7ed11162215c
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Wed Dec 8 19:54:15 2021 +0200

35. gmscompat: System.exit(1) if package uninstallation is declined

commit e161b716f6f71fd284fd7a7979fb85e315d89378
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Thu Nov 25 21:56:12 2021 +0200

36. gmscompat: use a reliable "is app foreground" check

    Previous check returned a false positive shortly after activity was paused,
    which led to startActivity() silently failing.

commit 187da4a81d80750c31fe1988eb940e8ba0569e7e
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Thu Nov 25 21:53:44 2021 +0200

37. gmscompat: make sure PackageInstaller UI returns a result

commit 3a62ed8c7826fc4560998ee955f3ba6fa9e2230f
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Thu Nov 25 21:46:42 2021 +0200

38. gmscompat: fix push notifications in secondary user profiles

    UserManager.isUserUnlocked(userId) returns whether a user exited the Direct Boot mode.
    This method requires a restricted permission if userId parameter differs from the current userId.
    GMS called this method with userId 0 in both primary (userId == 0) and secondary (userId != 0)
    profiles. userId was always 0 likely because of the stubbed out
    UserManager.getUserSerialNumber(userId),
    which always returned 0 as a workaround to a different issue.

commit 879d8337ccd843dd9f06d46908d087bb5f17faf1
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Tue Nov 23 21:02:26 2021 +0200

39. gmscompat: mark confirmation notification from Play Store as ongoing

    Play Store will wait for confirmation indefinitely if notification is dismissed.
    Ongoing notifications can't be dismissed (swiped away) by the user.

commit 653903f6f98727323eef7b2aa28c0b4d8e60c523
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Mon Nov 22 17:56:16 2021 +0200

40. gmscompat: compatibility with Play Store self-update

commit 1a5d379c1ae080fdac5e13e86cf650e21b9d5574
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Fri Nov 19 13:48:41 2021 +0200

41. minor style fix

commit 070f69019a41084ff7770de88f147b3dfef464b4
Author: Daniel Micay <danielmicay@gmail.com>
Date:   Thu Nov 18 12:04:59 2021 -0500

42. gmscompat: improve Play Store compatibility

    Implements package (un)installation confirmation handling and
    enables unattended app updates.

commit 1fbb34d2c0b86bbdf06203cb9202ac712122d469
Author: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Date:   Tue Nov 16 18:54:30 2021 +0200

43. gmscompat: use new API for long-running AppOps

    Android 12 added startProxyOpNoThrow and finishProxyOp so we no longer
    need to use noteProxyOpNoThrow as an approximation.

commit d31b261bca47a81ef1b6a0762c9d148b55c76755
Author: Daniel Micay <danielmicay@gmail.com>
Date:   Sat Nov 13 18:38:39 2021 -0500

44. gmscompat: Handle all exact alarm denials

    java.lang.SecurityException: Caller com.google.android.gms needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
            at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
            at android.os.Parcel.createException(Parcel.java:2409)
            at android.os.Parcel.readException(Parcel.java:2392)
            at android.os.Parcel.readException(Parcel.java:2334)
            at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:359)
            at android.app.AlarmManager.setImpl(AlarmManager.java:948)
            at android.app.AlarmManager.setImpl(AlarmManager.java:908)
            at android.app.AlarmManager.set(AlarmManager.java:818)
            at usv.k(:com.google.android.gms@213314046@21.33.14 (150400-395723304):1)
            at usv.o(:com.google.android.gms@213314046@21.33.14 (150400-395723304):0)
            at usv.e(:com.google.android.gms@213314046@21.33.14 (150400-395723304):2)
            at com.google.android.contextmanager.controller.EventHandler$AlarmSetter.c(:com.google.android.gms@213314046@21.33.14 (150400-395723304):8)
            at exr.d(:com.google.android.gms@213314046@21.33.14 (150400-395723304):3)
            at ext.l(:com.google.android.gms@213314046@21.33.14 (150400-395723304):0)
            at evr.a(:com.google.android.gms@213314046@21.33.14 (150400-395723304):143)
            at ext.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):2)
            at exp.handleMessage(:com.google.android.gms@213314046@21.33.14 (150400-395723304):3)
            at uwe.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):2)
            at uwo.c(:com.google.android.gms@213314046@21.33.14 (150400-395723304):6)
            at uwo.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):8)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
            at vcm.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):0)
            at java.lang.Thread.run(Thread.java:920)

commit 53466c12c474aef21f985f21a5bf7690e7f77f8e
Author: Danny Lin <danny@kdrag0n.dev>
Date:   Wed Oct 20 16:06:40 2021 -0700

45. net: Notify ConnectivityService of runtime permission changes

    ConnectivityService needs permission change events in order to enforce
    INTERNET permission updates correctly at runtime.

commit 72a9ec31663b5f2a24d570dfcf6fcc999dcd4f79
Author: Danny Lin <danny@kdrag0n.dev>
Date:   Tue Oct 5 16:27:43 2021 -0700


Signed-off-by: Danny Lin <danny@kdrag0n.dev>
Signed-off-by: Daniel Micay <danielmicay@gmail.com>
Signed-off-by: Dmitry Muhomor <muhomor.dmitry@gmail.com>
Signed-off-by: Semavi Ulusoy <doc.divxm@gmail.com>
Change-Id: Ib95425d3c9c03872b6d5ff0875313f5f9364a48d