fw_base: Revert "Sharesheet: Set max ranked items to 8"
frameworks/base/core/java/com/android/internal/app/ChooserActivity.java:2858: er
ror: cannot find symbol
        return MAX_TARGETS_PER_ROW_LANDSCAPE;

This reverts commit 8180af45350b20f7a4d57e719f6c9256bb21a8b3.

Change-Id: I4355df80d89123314a6df8277939097eac510bd5