SystemUI: Add heads up tile
Squashed:
    commit ed95b5501a83055071b7705f1f16c4e08850f46d
    Author: Pranav Vashi <neobuddy89@gmail.com>
    Date:   Sat May 5 23:30:36 2018 +0300

        Slashify and improve heads up tile

        Change-Id: Id38ef34107619ae4f3a32229bac168cdf10cb007

    commit 7fb7847017ef57afba7b06c200ae423d84841d93
    Author: maxwen <max.weninger@gmail.com>
    Date:   Fri Apr 13 03:32:51 2018 +0200

        SystemUI: stop crashing qs tiles during boot

        this triggers my ocd
        continues a579c2430f1a0bf088023b4283dcec37776c070d

        Change-Id: I31719b595cb50a330f26e25074243e04c06f63c1

    commit b1889e0b8ec01062f837eb9c9b981dee323a13d6
    Author: doc HD <doc.divxm@gmail.com>
    Date:   Thu Dec 14 10:49:32 2017 +0300

        fwb: implement the inherited abstract method for Custom Tiles

        Example:
        ERROR: /home/doc/aicpO8/frameworks/base/packages/SystemUI/src/com/android/systemui/qs/tiles/HeadsUpTile.java:34.14: The type HeadsUpTile must implement the inherited abstract method QSTileImpl<QSTile.BooleanState>.handleSetListening(boolean)
        ERROR: /home/doc/aicpO8/frameworks/base/packages/SystemUI/src/com/android/systemui/qs/tiles/HeadsUpTile.java:113.17: The method setListening(boolean) of type HeadsUpTile must override or implement a supertype method

        Change-Id: Ibb0d1fe884ef8d694cb687697dfd9a393f24293c

Change-Id: I0e3cff73752c59d804dcec43b86524c2e8df4f57