fw_base: udpfs: get inline with LoS and prepare for Android-12L merge
1. Revert "udfps: Allow devices to pulse onFingerDown instead of waking the screen"
2. Revert "fwb: Add overlay for udfps vendor code"
3. Revert "udfps: Add support for udfps on aod without having dedicated sensor"

Reason:
frameworks/base/services/core/java/com/android/server/biometrics/sensors/fingerp
rint/hidl/FingerprintAuthenticationClient.java:108: error: cannot find symbol
            mUdfpsOverlayController.onAcquired(getSensorId(), acquiredInfo, vend
orCode);
            ^
  symbol:   variable mUdfpsOverlayController
  location: class FingerprintAuthenticationClient

There is no "mUdfpsOverlayController" variable since: https://github.com/AICP/frameworks_base/commit/dce40910b1f4fcd8ffe522225839814e12860620

Change-Id: Ie72c853ebd8767f027787475d8c30cd352e9ff3a